name: 'Supabase action'
description: 'Provide a description here'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  database_url:
    description: 'Postgres DataBase URL of your supabase project'
    required: true
  timezone:
    description: 'file path Format time zone'
    required: true
    default: 'UTC'
  backup_path:
    description: 'directory to backup support date-fns format pattern'
    required: true
    default: 'backup/yyyy-MM-ddTHH:mm:ssZ'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
