name: 'Supabase backup action'
description: 'Backup supabase with its own cli in git repo'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  database_url:
    description: 'Postgres DataBase URL of your supabase project'
    required: true
  timezone:
    description: 'file path Format time zone'
    required: true
    default: 'UTC'
  backup_path:
    description: 'directory to backup support date-fns format pattern'
    required: true
    default: "'backup/'t-yyyy-MM-dd'T'HH:mm:ss'Z'"

# Define your outputs here.
outputs:
  files:
    description: 'Output file paths'

runs:
  using: node20
  main: dist/index.js
